export const PRODUCTS = [
  {
    id: 1,
    uri: require("../assets/images/siamChicken.jpeg"),
    name: "Siamese Hybrid Chicken",
    price: "₹200/Kg",
    discount: "20%",
    originalPrice: "₹250/Kg ",
    qty: 0,
    rs: 200,
  },
  {
    id: 2,
    uri: require("../assets/images/chicken.jpg"),
    name: "Vietanamese Turkey",
    price: "₹200/Kg",
    discount: "20%",
    originalPrice: "₹250/Kg ",
    qty: 0,
    rs: 200,
  },
  {
    id: 3,
    uri: require("../assets/images/ch1.jpg"),
    name: "Chicken",
    price: "₹200/Kg",
    discount: "20%",
    originalPrice: "₹250/Kg ",
    qty: 0,
    rs: 200,
  },
  {
    id: 4,
    uri: require("../assets/images/ch2.jpg"),
    name: "Chicken2",
    price: "₹200/Kg",
    discount: "20%",
    originalPrice: "₹250/Kg ",
    qty: 0,
    rs: 200,
  },
];
export const RECOMMEDNDED = [
  {
    id: 1,
    uri: require("../assets/food/0.jpg"),
    name: "WaterMelon",
    price: "₹200",
    qty: 0,
  },
  {
    id: 2,
    uri: require("../assets/food/1.jpg"),
    name: "Papaya",
    price: "₹200",
    qty: 0,
  },
  {
    id: 3,
    uri: require("../assets/food/2.jpg"),
    name: "Tea",
    price: "₹200",
    qty: 0,
  },
  {
    id: 4,
    uri: require("../assets/food/3.jpg"),
    name: "Snacks",
    price: "₹200",
    qty: 0,
  },
];
